[package]
name = "axis_arena"
version = "0.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"
spawn = "sozo execute axis_arena-actions spawn_agent --wait"
move = "sozo execute axis_arena-actions move_agent --wait"
attack = "sozo execute axis_arena-actions attack_agent --wait"
think = "sozo execute axis_arena-actions think --wait"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo.git", tag = "sozo/v1.8.6" }
starknet = "2.13.1"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[dev-dependencies]
cairo_test = "2.13.1"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "sozo/v1.8.6" }
